# Generated by Django 4.1.5 on 2023-01-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('regNo', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('phoneNo', models.CharField(max_length=50)),
                ('dateTime', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
