# Generated by Django 4.1.5 on 2023-01-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='dateTime',
            new_name='borrowDate',
        ),
        migrations.AddField(
            model_name='borrow',
            name='returnedDate',
            field=models.CharField(default='Not Returned', max_length=50),
        ),
    ]
