# Generated by Django 4.1.5 on 2023-01-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdb', '0002_rename_datetime_borrow_borrowdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='status',
            field=models.CharField(default='Not Returned', max_length=20),
        ),
    ]
