# Generated by Django 4.1.5 on 2023-01-29 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdb', '0003_alter_borrow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrowDate',
            field=models.CharField(default=datetime.date(2023, 1, 29), max_length=50),
        ),
    ]
